apiVersion: v1
kind: Service
metadata:
  name: orderwebservice
  labels:
    app: orderwebservice
spec:
  type: LoadBalancer
  selector:
    app: orderwebservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
